# ==========================================
# TESTCONTAINER'S CONFIGURATION DRIVER
# ==========================================
spring.datasource.driverClassName=org.testcontainers.jdbc.ContainerDatabaseDriver

spring.datasource.url=jdbc:tc:postgresql:16:///testdb?TC_INITSCRIPT=file:src/test/resources/init.sql

spring.datasource.username=test
spring.datasource.password=test

# ==========================================
# HIBERNATE AND JPA FOR POSTGRES
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# ==========================================
# SERVER
# ==========================================
server.port=0